version: '3'

services:
  django:
    build:
      context: .
      dockerfile: etc/Dockerfile-django
    hostname: django
    command: ./run.sh
    volumes:
      - ./logs:/logs
      - ./src:/code
    ports:
      - "3333:3333"
    env_file:
      - .env
    stdin_open: true
    tty: true

  nginx:
    restart: always
    build:
      context: .
      dockerfile: etc/Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./logs:/logs
      - ./src:/code
    links:
      - django:django
